name: Deploy to Fly.io DEV

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
      - fly.toml
      
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: dev
      - uses: superfly/flyctl-actions/setup-flyctl@master


      - run: |
          #Set New Secrets
          flyctl secrets set CF_TOKEN="${{ secrets.CF_TOKEN }}" --stage
          flyctl deploy --now --no-public-ips -a $FLY_APP --no-cache --local-only
        env:
          FLY_APP: ${{ secrets.FLY_APP }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}