name: Deploy to Fly.io

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - fly.toml

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: superfly/flyctl-actions/setup-flyctl@master


      - run: |
          #Set New Secrets
          flyctl secrets set CF_TOKEN="${{ secrets.CF_TOKEN }}" --stage
          flyctl deploy --now --no-public-ips -a $FLY_APP --no-cache --local-only
          #flyctl deploy --now --no-public-ips -a $FLY_APP --no-cache --local-only
        env:
          FLY_APP: ${{ secrets.FLY_APP }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}