name: Test deploy
on: workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@master
       with:
         ref: dev
     - name: Run other repo workflow
       uses: MartinatorTime/Github-Workflows/Fly-Deploy/deploy-fly-dev.yml@main
       with:
         FLY_APP: ${{ secrets.FLY_APP }}
         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}